<?php
return array(
            'goods'=>array(
                    array(
                        'file'=>'goods_search.php',
                        'name'=>'商品管理',
                        'action'=>array(
                                array(
                                  'action_type'=>'copty_goods_id_to_user_id',
                                  'name'=>'复制商品id到user_id',
                                ),
                                array(
                                  'action_type'=>'add',
                                  'name'=>'添加商品',
                                ),
                                array(
                                  'action_type'=>'copy',
                                  'name'=>'复制商品',
                                ),
                                array(
                                  'action_type'=>'do_edit_status',
                                  'name'=>'执行活动编辑状态',
                                ),
                                array(
                                  'action_type'=>'edit_status',
                                  'name'=>'活动编辑状态界面',
                                ),
                                array(
                                  'action_type'=>'chstatus',
                                  'name'=>'审核',
                                ),
                                array(
                                  'action_type'=>'chshow',
                                  'name'=>'上架',
                                ),
                                array(
                                  'action_type'=>'edit',
                                  'name'=>'编辑',
                                ),
                                array(
                                  'action_type'=>'goods_export',
                                  'name'=>'原good.php导出功能',
                                ),
                                array(
                                  'action_type'=>'usergoodslist',
                                  'name'=>'用户商品列表',
                                ),
                                array(
                                  'action_type'=>'order_management',
                                  'name'=>'场次管理',
                                ),
                                array(
                                  'action_type'=>'goods_list',
                                  'name'=>'原good.php商品列表',
                                ),
                                array(
                                  'action_type'=>'export',
                                  'name'=>'导出',
                                ),
                                array(
                                  'action_type'=>'default',
                                  'name'=>'默认商品列表',
                                ),
                        )
                    ),
            ),
            'seller'=>array(
                    array(
                        'file'=>'seller_search.php',
                        'name'=>'商家管理',
                        'action'=>array(
                            array(
                              'action_type'=>'addstore',
                              'name'=>'添加商店',
                            ),
                            array(
                              'action_type'=>'addcompany',
                              'name'=>'添加公司',
                            ),
                            array(
                              'action_type'=>'addseller',
                              'name'=>'添加商家',
                            ),
                            array(
                              'action_type'=>'chsellerstatus',
                              'name'=>'改变商家状态',
                            ),
                            array(
                              'action_type'=>'chcompanystatus',
                              'name'=>'改变公司状态',
                            ),
                            array(
                              'action_type'=>'chstorestatus',
                              'name'=>'改变店铺状态',
                            ),
                            array(
                              'action_type'=>'editseller',
                              'name'=>'编辑商家',
                            ),
                            array(
                              'action_type'=>'editcompany',
                              'name'=>'编辑公司',
                            ),
                            array(
                              'action_type'=>'editprofile',
                              'name'=>'编辑商家资料',
                            ),
                            array(
                              'action_type'=>'editstore',
                              'name'=>'编辑店铺',
                            ),
                            array(
                              'action_type'=>'companylist',
                              'name'=>'公司列表',
                            ),
                            array(
                              'action_type'=>'storelist',
                              'name'=>'店铺列表',
                            ),
                            array(
                              'action_type'=>'seller_list',
                              'name'=>'原seller.php商家列表',
                            ),
                            array(
                              'action_type'=>'seller_export',
                              'name'=>'原seller.php商家导出功能',
                            ),
                            array(
                              'action_type'=>'export',
                              'name'=>'导出',
                            ),
                            array(
                              'action_type'=>'default',
                              'name'=>'默认商家列表',
                            ),

                        )
                    ),
                    array(
                        'file'=>'seller_sq.php',
                        'name'=>'商家申请管理',
                        'action'=>array(
                            array(
                                'action_type'=>'check',
                                'name'=>'审核',
                            ),
                            array(
                                'action_type'=>'info',
                                'name'=>'详情',
                            ),
                            array(
                                'action_type'=>'default',
                                'name'=>'默认列表',
                            )
                        )
                    ),
                    array(
                        'file'=>'server_sq.php',
                        'name'=>'商家服务申请管理',
                        'action'=>array(
                            array(
                                'action_type'=>'check',
                                'name'=>'审核',
                            ),
                            array(
                                'action_type'=>'info',
                                'name'=>'详情',
                            ),
                            array(
                                'action_type'=>'default',
                                'name'=>'默认列表',
                            )
                        )
                    ),
                    array(
                        'file'=>'seller_rating.php',
                        'name'=>'商家评级管理',
                        'action'=>array(
                            array(
                                'action_type'=>'default',
                                'name'=>'商家评级',
                            ),

                        )
                    ),
                    array(
                        'file'=>'seller_relate_org.php',
                        'name'=>'商家管理机构管理',
                        'action'=>array(
                            array(
                                'action_type'=>'insert',
                                'name'=>'机构插入',
                            ),
                            array(
                                'action_type'=>'default',
                                'name'=>'机构列表',
                            ),

                        )
                    ),
                    array(
                        'file'=>'seller_scalping.php',
                        'name'=>'刷单商家管理',
                        'action'=>array(
                            array(
                                'action_type'=>'get_seller_name',
                                'name'=>'获取seller_name',
                            ),
                            array(
                                'action_type'=>'scalping_info',
                                'name'=>'刷单详情',
                            ),
                            array(
                                'action_type'=>'add_seller',
                                'name'=>'添加商家',
                            ),
                            array(
                                'action_type'=>'edit_seller',
                                'name'=>'编辑商家',
                            ),
                            array(
                                'action_type'=>'default',
                                'name'=>'默认刷单列表',
                            ),

                        )
                    ),
                    array(
                        'file'=>'seller_scalping_check_log.php',
                        'name'=>'刷单商家检查日志',
                        'action'=>array(
                            array(
                                'action_type'=>'rule_info',
                                'name'=>'规则情况',
                            ),
                            array(
                                'action_type'=>'export',
                                'name'=>'导出',
                            ),
                            array(
                                'action_type'=>'default',
                                'name'=>'列表',
                            )
                        )
                    ),
                    array(
                        'file'=>'seller_scalping_white_list.php',
                        'name'=>'刷单商家白名单',
                        'action'=>array(
                            array(
                                'action_type'=>'white_list_info',
                                'name'=>'白名单详情',
                            ),
                            array(
                                'action_type'=>'add_white_list',
                                'name'=>'添加白名单列表',
                            ),
                            array(
                                'action_type'=>'remove_white_list',
                                'name'=>'移除白名单',
                            ),
                            array(
                                'action_type'=>'default',
                                'name'=>'默认白名单列表',
                            ),
                        )
                    ),
            ),
            'order'=>array(
                array(
                    'file'=>'mall_bill.php',
                    'name'=>'订单',
                    'action'=>array(
                        array(
                            'action_type'=>'list',
                            'name'=>'订单列表',
                        ),
                        array(
                            'action_type'=>'detail',
                            'name'=>'订单详情',
                        ),
                        array(
                            'action_type'=>'export_order',
                            'name'=>'导出订单',
                        ),
                        array(
                            'action_type'=>'close_order',
                            'name'=>'关闭订单',
                        ),
                        array(
                            'action_type'=>'sign_order',
                            'name'=>'签到订单',
                        ),
                        array(
                            'action_type'=>'accept_order',
                            'name'=>'接受订单',
                        ),
                    )
                ),
            ),
            'user'=>array(
                array(
                    'file'=>'user_list.php',
                    'name'=>'用户列表管理',
                    'action'=>array(
                        array(
                            'action_type'=>'default',
                            'name'=>'默认用户列表',
                        ),
                    )
                ),
            ),
			 
            
            
);
?>