<?php
return array(
        array(
            'head_img'=>'resources/images/mall_admin.png',
            'head_name'=>'商城后台',
            'son'=>array(
                array(
                    'son_name'=>'商家/商品/订单',
                    'son_link'=>'http://www.yueus.com/yue_admin/task/index.php',
                    'acl_relate'=>array(1,17,3),
                ),
                array(
                    'son_name'=>'接单中心',
                    'son_link'=>'http://www.yueus.com/yue_admin/take_order/order_list.php',
                    'acl_relate'=>array(320),
                ),
                array(
                    'son_name'=>'OA系统后台',
                    'son_link'=>'http://www.yueus.com/yue_admin/oa/',
                    'acl_relate'=>array(278),
                ),
                array(
                    'son_name'=>'代运营管理后台',
                    'son_link'=>'http://www.yueus.com/yue_admin/operate_agent/',
                    'acl_relate'=>array(273),
                ),
                array(
                    'son_name'=>'Q&A后台',
                    'son_link'=>'http://www.yueus.com/yue_admin/qa/',
                    'acl_relate'=>array(274),
                ),
                
                
            )
        ),
        array(
            'head_img'=>'resources/images/member_admin.png',
            'head_name'=>'会员关系',
            'son'=>array(
                array(
                    'son_name'=>'CRM管理',
                    'son_link'=>'http://report.yueus.com/crm/consumer.php',
                    'acl_relate'=>array(325),
                ),
                array(
                    'son_name'=>'身份证审核管理',
                    'son_link'=>'http://www.yueus.com/yue_admin/operate/',
                    'acl_relate'=>array(276),
                ),
                array(
                    'son_name'=>'举报/黑名单管理',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/inform/index.php',
                    'acl_relate'=>array(260),
                ),
                array(
                    'son_name'=>'手机信息管理',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/sms_service/index.php',
                    'acl_relate'=>array(269),
                ),
                array(
                    'son_name'=>'结算机构',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/org_add',
                    'acl_relate'=>array(275),
                ),
                array(
                    'son_name'=>'普通机构',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/ordinary_orgmg',
                    'acl_relate'=>array(354),
                ),
                array(
                    'son_name'=>'信息推送管理',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/message',
                    'acl_relate'=>array(307),
                ),
                
                
            )
        ),
        array(
            'head_img'=>'resources/images/content_admin.png',
            'head_name'=>'内容运营',
            'son'=>array(
                array(
                    'son_name'=>'榜单系统',
                    'son_link'=>'http://www.yueus.com/yue_admin/cms/',
                    'acl_relate'=>array(277),
                ),
                array(
                    'son_name'=>'专题管理',
                    'son_link'=>'http://www.yueus.com/yue_admin/topic/index.php',
                    'acl_relate'=>array(268),
                ),
                array(
                    'son_name'=>'CMS内容管理',
                    'son_link'=>'http://www.yueus.com/yue_admin/mall_cms/cms_list.php',
                    'acl_relate'=>array(271),
                ),
                array(
                    'son_name'=>'图文内容审核',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/audit',
                    'acl_relate'=>array(270),
                ),
                array(
                    'son_name'=>'内容模块',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/new_rank/index.php',
                    'acl_relate'=>array(272),
                ),
                array(
                    'son_name'=>'微信公众号后台',
                    'son_link'=>'http://www.yueus.com/yue_admin/wxpub/',
                    'acl_relate'=>array(362),
                )
            )
        ),
        array(
            'head_img'=>'resources/images/template_admin.png',
            'head_name'=>'模板管理',
            'son'=>array(
                array(
                    'son_name'=>'消息推送模板管理',
                    'son_link'=>'http://www.yueus.com/yue_admin/template/index.php',
                    'acl_relate'=>array(261),
                )
            )
        ),
        array(
            'head_img'=>'resources/images/data_admin.png',
            'head_name'=>'数据分析',
            'son'=>array(
                array(
                    'son_name'=>'数据报表',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/report',
                    'acl_relate'=>array(259),
                ),
                array(
                    'son_name'=>'优惠券数据管理',
                    'son_link'=>'http://ypay.yueus.com/ecpay_admin/index.php',
                    'acl_relate'=>array(267),
                ),
                array(
                    'son_name'=>'数据分析系统',
                    'son_link'=>'http://report.yueus.com',
                    'acl_relate'=>array(331),
                ),
            )
        ),
        array(
            'head_img'=>'resources/images/system_admin.png',
            'head_name'=>'系统管理',
            'son'=>array(
                array(
                    'son_name'=>'sql错误(繁忙)系统',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/sql_err_log/index.php',
                    'acl_relate'=>array(313),
                ),
                array(
                    'son_name'=>'监控的后台管理',
                    'son_link'=>'http://www.yueus.com/yue_admin_v2/monitor/index.php',
                    'acl_relate'=>array(337),
                ),
            )
        ),
        array(
            'head_img'=>'resources/images/promotion_admin.png',
            'head_name'=>'促销管理',
            'son'=>array(
                array(
                    'son_name'=>'优惠券管理系统',
                    'son_link'=>'http://www.yueus.com/yue_admin/coupon/index.php',
                    'acl_relate'=>array(265),
                )
            )
        ),
);
?>