<?php
return array(
        array(
            'head_name'=>'商城后台',
            'link'=>'http://www.yueus.com/yue_admin/task/',
            'acl_relate'=>array(1,17,3),
        ),
        array(
            'head_name'=>'内容后台',
            'link'=>'http://www.yueus.com/yue_admin_v2/new_rank_v2/',
            'acl_relate'=>array(272,268,277),
        ),
        array(
            'head_name'=>'客服后台',
            'link'=>'http://www.yueus.com/yue_admin_v2/audit/#this',
            'acl_relate'=>array(273,274,71,260,269,270,278),
        ),
        array(
            'head_name'=>'接单中心后台',
            'link'=>'http://www.yueus.com/yue_admin/take_order/',
            'acl_relate'=>array(320,268),
        ),
        array(
            'head_name'=>'CRM后台',
            'link'=>'http://report.yueus.com/crm/consumer.php',
            'acl_relate'=>array(399),
        ),
        array(
            'head_name'=>'领券中心后台',
            'link'=>'http://www.yueus.com/yue_admin/coupon/',
            'acl_relate'=>array(97,267),
        ),
        array(
            'head_name'=>'机构后台',
            'link'=>'http://www.yueus.com/yue_admin_v2/org_add/',
            'acl_relate'=>array(275,354),
        ),
        array(
            'head_name'=>'cms内容管理',
            'link'=>'http://www.yueus.com/yue_admin/mall_cms/',
            'acl_relate'=>array(271,342,362),
            
        ),
        array(
            'head_name'=>'数据报表',
            'link'=>'http://www.yueus.com/yue_admin_v2/report/index.php',
            'acl_relate'=>array(259),
            
        ),
        array(
            'head_name'=>'经营后台',
            'link'=>'http://report.yueus.com/',
            'acl_relate'=>array(494),
            
        ),
);
?>