<?php
return array(
			 1=>array(//上门服务 
			          array(
					        'name'=>'可服务区域',
					        'key'=>'message',
					        'mess'=>'',
					        'input'=>3,
							),					  
			          array(
					        'name'=>'服务开始时间',
					        'key'=>'ac_time',
					        'mess'=>'',
					        'input'=>7,
							),					  
					  ),
			 2=>array(//定点服务
			          array(
					        'name'=>'省 / 市 / 区',
					        'key'=>'location_id',
					        'mess'=>'',
					        'input'=>8,
							),					  
			          array(
					        'name'=>'详细服务地址',
					        'key'=>'address',
					        'mess'=>'',
					        'input'=>3,
							),					  
			          array(
					        'name'=>'地图定位',
					        'key'=>'lng_lat',
					        'mess'=>'',
					        'input'=>3,
							),					  
			          array(
					        'name'=>'服务开始时间',
					        'key'=>'ac_time',
					        'mess'=>'',
					        'input'=>7,
							),					  
					  ),
			 3=>array(//线上服务
			          array(
					        'name'=>'线上渠道说明',
					        'key'=>'message',
					        'mess'=>'',
					        'input'=>3,
							),					  
			          array(
					        'name'=>'服务开始时间',
					        'key'=>'ac_time',
					        'mess'=>'',
					        'input'=>7,
							),					  
					  ),
			 4=>array(//实物寄送
			          array(
					        'name'=>'寄送范围说明',
					        'key'=>'message',
					        'mess'=>'',
					        'input'=>3,
							),					  
					  ),
			 5=>array(),//活动
			 
);
?>