<?php
return array(
			 1=>array(//上门服务 
			          'ac_time'=>array(
					        'name'=>'服务时间',
					        'key'=>'ac_time',
					        'type'=>'1',//时间
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
			          'location_id'=>array(
					        'name'=>'服务地区',
					        'key'=>'location_id',
					        'type'=>'2',//地区
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
			          'address'=>array(
					        'name'=>'地址',
					        'key'=>'address',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
			          'phone'=>array(
					        'name'=>'联系手机',
					        'key'=>'phone',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
					  ),
			 2=>array(//定点服务
			          'lng_lat'=>array(
					        'name'=>'地图定位',
					        'key'=>'lng_lat',
					        'type'=>'4',//地图
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
			          'ac_time'=>array(
					        'name'=>'服务时间',
					        'key'=>'ac_time',
					        'type'=>'1',//时间
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
			          'location_id'=>array(
					        'name'=>'服务地区',
					        'key'=>'location_id',
					        'type'=>'2',//地区
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
			          'address'=>array(
					        'name'=>'地址',
					        'key'=>'address',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
			          'phone'=>array(
					        'name'=>'联系手机',
					        'key'=>'phone',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
					  ),
			 3=>array(//线上服务
			          'ac_time'=>array(
					        'name'=>'服务时间',
					        'key'=>'ac_time',
					        'type'=>'1',//时间
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
			          'phone'=>array(
					        'name'=>'联系手机',
					        'key'=>'phone',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
					  ),
			 4=>array(//实物寄送
			          'name'=>array(
					        'name'=>'收货人',
					        'key'=>'name',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
			          'phone'=>array(
					        'name'=>'联系手机',
					        'key'=>'phone',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
			          'location_id'=>array(
					        'name'=>'服务地区',
					        'key'=>'location_id',
					        'type'=>'2',//地区
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
			          'address'=>array(
					        'name'=>'地址',
					        'key'=>'address',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),					  
					  ),
			 5=>array(
			          'phone'=>array(
					        'name'=>'联系手机',
					        'key'=>'phone',
					        'type'=>'3',//输入框
					        'mess'=>'',
					        'is_input'=>1,
					        'value'=>'',
							),
			 ),//活动
			 
);
?>